import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const main = readFileSync('src/main.tsx', 'utf8');
const app = readFileSync('src/AppV3.tsx', 'utf8');
const css = readFileSync('src/styles.css', 'utf8');
const indexHtml = readFileSync('index.html', 'utf8');
const deliveryNote = readFileSync('src/lib/deliveryNote.ts', 'utf8');

assert.equal(main.includes("./ui-v2.css"), false, 'React entry should not load the rounded v2 shell when matching old SPR');
assert.match(app, /id="searchBlock"/, 'store shell should keep old SPR searchBlock node');
assert.match(app, /id="list"/, 'store shell should keep old SPR list node');
assert.match(app, /id="alphabetSidebar"/, 'store shell should keep old SPR alphabet sidebar node');
assert.match(app, /className="top-action-bar"/, 'store shell should render old top action bar');
assert.match(app, /function getInitialEmployeeFromUrl/, 'app should support old SPR emp URL entry');
assert.match(app, /URLSearchParams\(window\.location\.search\)/, 'app should read emp and employee_code query params like old SPR');
assert.match(app, /sessionStorage\.setItem\('current_employee_code'/, 'app should persist current employee code for old SPR entry compatibility');
assert.match(app, /openInitialEmployeeFromUrl/, 'bootstrap should auto-open stores when emp is provided');
assert.match(app, /门店总数：/, 'store list should show old SPR total-store summary text');
assert.match(app, /letter-group-title/, 'store list should group stores by first-letter headings');
assert.match(app, /📦 库存管理/, 'store gates should use old SPR stock label');
assert.match(app, /📊 卖进数据/, 'store gates should use old SPR report label');
assert.match(app, /🆕 新门店/, 'store gates should use old SPR new-store label');
assert.match(app, /id="liveAmountBanner"/, 'order page should render old live amount banner');
assert.match(app, /id="dateText"/, 'order page should render old visible dateText span');
assert.match(app, /order-date-action/, 'order page should use old hidden date picker trigger');
assert.match(app, /className="mix-box-toggle"/, 'mix box should use old toggle button class');
assert.match(app, /className="ios-picker"/, 'order quantities should use old select picker controls');
assert.match(app, /data-price-product/, 'price controls should keep old data-price-product hook');
assert.match(app, /className="float-submit"[^>]*>提交账单</, 'submit button should match old SPR label without live total appended');
assert.equal(app.includes('全部规格'), false, 'old SPR spec nav should not add a synthetic all-spec option');
assert.match(css, /body\.store-search-mode #searchBlock/, 'search mode CSS should target old searchBlock id');
assert.match(css, /\.mix-box-toggle/, 'CSS should contain old mix-box toggle styling');
assert.match(app, /openNewStoreManagement/, 'new-store gate should open a real management view, not an alert placeholder');
assert.match(app, /triggerCreateNewStore/, 'new-store flow should create a temporary NEW_ store before opening an order');
assert.match(app, /NEW_/, 'manual store flow should use NEW_ atom codes like old SPR');
assert.match(app, /deleteNewStore/, 'manual stores should expose a delete flow');
assert.match(app, /countStoreOrders/, 'manual store delete should check existing order history first');
assert.match(app, /deleteManualStore/, 'manual store delete should remove employee_store_assets rows');
assert.equal(app.includes("alert('新门店功能后续迁移')"), false, 'new-store gate must not stay as a placeholder alert');
assert.match(app, /已开单的新门店列表/, 'new-store management should show the old manual-store list label');
assert.match(app, /after-sales-wrap/, 'order loose row should expose old after-sales inline wrapper');
assert.match(app, /data-after-sales-wrap/, 'after-sales toggle should keep the old stable wrapper hook');
assert.match(app, /data-after-sales-panel/, 'after-sales panel should keep the old stable panel hook');
assert.match(app, /data-after-sales-select/, 'after-sales quantity picker should keep the old stable select hook');
assert.match(app, /after-sales-toggle/, 'order page should render the old after-sales toggle button');
assert.match(app, /after-sales-panel-label/, 'after-sales panel should render the old panel label');
assert.match(app, /收回数/, 'after-sales panel should use the old label text');
assert.match(app, /只算能卖的，收回增加库存/, 'after-sales panel should explain the stock effect like old SPR');
assert.match(css, /\.control-group\.after-sales-group \.sell-line/, 'after-sales CSS should align loose and whole rows as old SPR');
assert.match(css, /\.after-sales-panel\.open/, 'after-sales CSS should expose the old open panel layout');
assert.match(app, /qty-popup-mask/, 'quantity popup should render the old popup mask');
assert.match(app, /qty-popup-sheet/, 'quantity popup should render the old popup sheet');
assert.match(app, /qty-popup-grid qty-popup-grid-5/, 'quantity popup should use the old 5-column grid');
assert.match(app, /data-qty-value/, 'quantity popup should expose old number button hook');
assert.match(app, /data-qty-action="clear"/, 'quantity popup should expose old clear action hook');
assert.match(app, /qty-popup-trigger/, 'quantity selects should render popup trigger buttons');
assert.match(app, /qty-native-hidden/, 'native quantity selects should be visually hidden like old SPR');
assert.match(app, /售后数/, 'quantity popup should label after-sales quantity separately');
assert.match(css, /\.qty-popup-mask/, 'quantity popup CSS should include old mask styling');
assert.match(css, /\.qty-popup-number\.active/, 'quantity popup CSS should include old active number state');
assert.match(indexHtml, /html2canvas@1\.4\.1/, 'delivery note should load the old html2canvas renderer');
assert.match(app, /async function generateDeliveryNote/, 'delivery note buttons should call a real generator');
assert.match(app, /generateDeliveryNote\(row\.order_no, date, store\.store_name\)/, 'history delivery note button should pass order number, date, and store name');
assert.match(app, /<div className="history-item history-item-compact" role="button"/, 'history rows should not nest the delivery button inside another button');
assert.match(app, /generateDeliveryNote\(detail\.orderNo, detail\.orderDate, storeName\)/, 'detail delivery note button should pass current order context');
assert.match(app, /deliveryBusyOrderNo/, 'delivery note generation should disable buttons while rendering');
assert.match(deliveryNote, /function safeDeliveryFileName/, 'delivery note should keep old safe filename behavior');
assert.match(deliveryNote, /delivery-note-capture-wrap/, 'delivery note should render offscreen before capture');
assert.match(deliveryNote, /buildDeliveryNoteHtml/, 'delivery note should build the old printable table');
assert.match(deliveryNote, /link\.download/, 'delivery note should download the generated PNG directly');
assert.match(deliveryNote, /link\.click\(\)/, 'delivery note should click a temporary anchor like old SPR');
assert.doesNotMatch(deliveryNote, /delivery-note-overlay|delivery-note-preview-img|openDeliveryImageFullscreen/, 'delivery note should not regress to preview overlay flow');
assert.match(app, /async function editExistingOrder/, 'detail edit button should restore an existing order into the order editor');
assert.match(app, /orderItemsToDraftLines/, 'existing order edit should convert old items back to draft lines');
assert.match(app, /previousStockByBarcode/, 'existing order edit should keep old stock usage for delta stock updates');
assert.match(app, /orderNo: editingOrderNo/, 'existing order submit should reuse the original order number');
assert.match(app, /if \(screen === 'order' && editingOrderNo && detail\)/, 'back from editing an existing order should return to detail like old SPR');
assert.match(app, /setEditingOrderNo\(null\)/, 'leaving order edit should clear the editing order state');
assert.match(app, /if \(screen === 'order' && store && String\(store\.atom_code\)\.startsWith\('NEW_'\)\)/, 'back from a new-store order should return to new-store management');
assert.match(app, /async function deleteOrder/, 'detail delete button should run a real delete flow');
assert.match(app, /deleteExistingOrder/, 'detail delete should call the API delete and stock restore helper');
assert.match(app, /确定删除本笔记录并返还库存量吗/, 'delete flow should keep the old SPR confirmation wording');
assert.match(app, /onClick=\{\(\) => editExistingOrder\(detail\.orderNo\)\}/, 'detail edit button should be wired to editExistingOrder');
assert.match(app, /onClick=\{\(\) => deleteOrder\(detail\.orderNo\)\}/, 'detail delete button should be wired to deleteOrder');
assert.match(app, /parseAfterSaleRemark/, 'detail should parse after-sales remark metadata');
assert.match(app, /afterSaleMap/, 'detail state should carry after-sales quantities');
assert.match(app, /order-detail-line-danger/, 'detail should render old after-sales danger line');
assert.match(app, /order-detail-row-danger/, 'after-sales-only detail rows should use old danger row');
assert.match(app, /orderItemsToDraftLines\(data\.items, products, parseAfterSaleRemark/, 'edit should restore after-sales quantities from order remark');
assert.match(app, /type ReportPreset = 'today' \| 'yesterday' \| 'week' \| 'month' \| 'all' \| 'custom'/, 'report should support the old preset set');
assert.match(app, /reportPreset/, 'report should track the active preset like old SPR');
assert.match(app, /function getReportRange/, 'report should derive old SPR date ranges');
assert.match(app, /\['today', '今天'\], \['yesterday', '昨天'\], \['week', '本周'\], \['month', '本月'\], \['all', '全部'\]/, 'report filters should render old preset buttons');
assert.match(app, /id="reportDateInput"/, 'report custom date should keep the old reportDateInput hook');
assert.match(app, /openReport\('custom', event\.target\.value\)/, 'report custom date should reload the custom day');
assert.match(app, /preset === 'all'[\s\S]*start: '', end: ''/, 'report all preset should query without date bounds');
assert.match(app, /function formatQtyToUnits/, 'stock page should use old SPR stock-specific unit formatter');
assert.match(app, /件 \$\{boxes\}中盒/, 'three-level stock display should include 件 and 中盒 units');
assert.match(app, /formatQtyToUnits\(total, product\.pcs_per_case, product\.pcs_per_box, unitOf\(product\)\)/, 'stock page should render stock with the stock-specific formatter');
assert.doesNotMatch(app, /stock-qty[\s\S]*formatStockQty\(total, product\)/, 'stock page should not use the sales whole-loose formatter');
assert.match(app, /detailFromReport/, 'detail screen should remember when it was opened from report');
assert.match(app, /openReportDetail\(row: ReportRow\)/, 'report rows should open detail with report context');
assert.match(app, /setStore\(\{ employee_code: employee\?\.employee_code \|\| '', atom_code: row\.atomCode, store_name: row\.storeName \}\)/, 'report detail should set current store context from the report row');
assert.match(app, /openDetail\(row\.order_no, true\)/, 'report detail should pass the from-report flag');
assert.match(app, /detailFromReport \? void openReport\(reportPreset, reportDate\) : setScreen\('history'\)/, 'back from report detail should return to report');
assert.match(app, /if \(detailFromReport\) await openReport\(reportPreset, reportDate\)/, 'deleting from report detail should return to report');
